export const ROLES = Object.freeze({
  ADMIN: "admin",
  SUBADMIN: "subadmin",
  DEPARTMENT: "department",
});

export const TIME_PERIODS = Object.freeze({
  TODAY: "today",
  YESTERDAY: "yesterday",
  DAILY: "daily",
  WEEKLY: "weekly",
  MONTHLY: "monthly",
  YEARLY: "yearly",
  CUSTOM: "custom",
});

export const TIME_PERIOD_OPTIONS = Object.freeze([
  { value: TIME_PERIODS.TODAY, label: "Today" },
  { value: TIME_PERIODS.YESTERDAY, label: "Yesterday" },
  { value: TIME_PERIODS.DAILY, label: "Daily" },
  { value: TIME_PERIODS.WEEKLY, label: "Weekly" },
  { value: TIME_PERIODS.MONTHLY, label: "Monthly" },
  { value: TIME_PERIODS.YEARLY, label: "Yearly" },
  { value: TIME_PERIODS.CUSTOM, label: "Custom" },
]);

export const STATUSES = Object.freeze({
  NEW: "New",
  ASSIGNED: "Assigned",
  PENDING: "Pending",
  CONFIRMED: "Confirmed",
  RESOLVED: "Resolved",
  REPLIED: "Replied",
  SCHEDULED: "Scheduled",
  LIVE: "Live",
  COMPLETED: "Completed",
  CANCELLED: "Cancelled",
});

export const DASHBOARD_LABELS = Object.freeze({
  TITLE: "Dashboard",
  SUBTITLE:
    "CRM overview with growth, activity, charts, and operational queues",
  KPI_CUSTOMERS: "Customers",
  KPI_APPOINTMENTS: "Appointments",
  KPI_SESSIONS: "Sessions",
  KPI_CONTENT_PUBLISHED: "Content published",
  PANEL_APPOINTMENTS_TREND: "Appointments trend",
  PANEL_APPOINTMENTS_TREND_SUBTITLE: "Booked vs completed vs cancelled",
  PANEL_SESSIONS_OVERVIEW: "Sessions overview",
  PANEL_SESSIONS_OVERVIEW_SUBTITLE: "Scheduled vs live vs completed",
  MODULES_TITLE: "Modules",
  MODULES_SUBTITLE: "Pregnancy ecosystem CRM modules",
  RECENT_ACTIVITY_TITLE: "Recent activity",
  RECENT_ACTIVITY_SUBTITLE: "Latest updates across CRM",
  ENQUIRIES_QUEUE_TITLE: "Enquiries queue",
  ENQUIRIES_QUEUE_SUBTITLE: "New / assigned / pending",
  APPOINTMENTS_QUEUE_TITLE: "Today appointments",
  APPOINTMENTS_QUEUE_SUBTITLE: "Operational view",
  OUTLET_REPORTS_TITLE: "Outlet reports",
  OUTLET_REPORTS_SUBTITLE: "Outlet-wise performance & workload",
  BADGE_LIVE: "Live",
  BADGE_CRM: "CRM",
  BADGE_OPS: "Ops",
  LABEL_ROLE: "Role",
  LABEL_NEW: "New",
  LABEL_PREV: "Prev",
  LABEL_MY_OUTLET: "My outlet",
  LABEL_ALL_OUTLETS: "All outlets",
  STAT_CUSTOMERS: "Customers",
  STAT_APPOINTMENTS: "Appointments",
  STAT_SESSIONS: "Sessions",
  STAT_ENQUIRIES: "Enquiries",
  ACTION_CREATE_CUSTOMER: "Create new customer entry",
  ACTION_CREATE_CUSTOMER_HINT: "Add manually to CRM",
  ACTION_ASSIGN_ENQUIRY: "Assign enquiry",
  ACTION_ASSIGN_ENQUIRY_HINT: "Route to department",
  ACTION_PUBLISH_TIP: "Publish new tip",
  ACTION_PUBLISH_TIP_HINT: "Content hub",
  ACTION_REVIEW_APPOINTMENTS: "Review appointment queue",
  ACTION_REVIEW_APPOINTMENTS_HINT: "Ops control",
  PANEL_GROWTH: "Growth & decline",
  PANEL_GROWTH_SUBTITLE: "Compare growth/decline across selected time period",
  PANEL_PUBLISHING: "Publishing",
  PANEL_PUBLISHING_SUBTITLE: "Tips / trimester / nutrition / meal plan",
  PUBLISH_TIPS: "Tips",
  PUBLISH_TRIMESTER_PLANS: "Trimester plans",
  PUBLISH_NUTRITION_PLANS: "Nutrition plans",
  PUBLISH_MEAL_PLANS: "Meal plans",
  PANEL_ACTIONS: "CRM actions",
  PANEL_ACTIONS_SUBTITLE: "Quick operations (wire later)",
});
